POST https://swym-assessment.azurewebsites.net/api/postTweetData?code=5bUlaFQ02PPGMxogLxBQvgO6EAiAHVifulW3wLmZopEgDB9dwCXiLQ==

{
"username":"rahul",
"location":"Pune",
"text":"first tweet"
}

###
POST https://swym-assessment.azurewebsites.net/api/postTweetData?code=5bUlaFQ02PPGMxogLxBQvgO6EAiAHVifulW3wLmZopEgDB9dwCXiLQ==

{
"username":"Anuj",
"location":"Pune",
"text":"first tweet"
}

###
POST https://swym-assessment.azurewebsites.net/api/postTweetData?code=5bUlaFQ02PPGMxogLxBQvgO6EAiAHVifulW3wLmZopEgDB9dwCXiLQ==

{
"username":"vivek",
"location":"Pune",
"text":"fifth tweet",

"tags": ["awesome-hashtag"]
}
###