POST https://swym-assessment.azurewebsites.net/api/postTweetData?code=5bUlaFQ02PPGMxogLxBQvgO6EAiAHVifulW3wLmZopEgDB9dwCXiLQ==

{
  "username":"vivek",
  "location":"Pune",
  "text":"first tweet",
  "tweetCount":101,
  "tags": ["awesome-hashtag"]
}